package controllers

var token string = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTQ4OTI5NjYsImlhdCI6MTU5NDg4NTc2NiwiaWQiOjMsInVzZXJuYW1lIjoiZGFtaW4ifQ.svTO5iW4p15NWOTw4NadaHgHtSTh8iKHWRCJjzV5BrA`
