definitions:
  controllers.Block:
    properties:
      difficulty:
        type: string
      gasLimit:
        type: integer
      gasUsed:
        type: integer
      miner:
        type: string
      nonce:
        type: integer
      number:
        type: string
      parentHash:
        type: string
      sha3Uncles:
        type: string
      timestamp:
        type: integer
      transactions:
        type: integer
    type: object
  controllers.ExistsContractParam:
    properties:
      abi:
        type: string
      address:
        type: string
      bin:
        type: string
      chain_id:
        description: 链id ,合约部署在那条链上
        type: integer
      description:
        type: string
      sol:
        type: string
      tx_hash:
        type: string
    required:
    - abi
    - description
    type: object
  controllers.JsonResult:
    properties:
      code:
        type: integer
      data:
        type: object
      err_msg:
        type: string
    required:
    - code
    type: object
  controllers.Node:
    properties:
      address:
        description: 地址
        type: string
      chain_id:
        description: 链id
        type: integer
      chain_name:
        type: string
      description:
        type: string
      is_https:
        type: boolean
      name:
        type: string
      network_id:
        type: integer
      port:
        description: 端口
        type: integer
      user_id:
        type: integer
    required:
    - address
    - chain_id
    - name
    - port
    type: object
  controllers.Transaction:
    properties:
      from:
        type: string
      gas:
        type: integer
      gasPrice:
        type: string
      hash:
        type: string
      input:
        items:
          type: integer
        type: array
      nonce:
        type: integer
      to:
        type: string
      value:
        type: string
    type: object
  controllers.TransactionReceipt:
    properties:
      blockHash:
        type: string
      blockNumber:
        type: string
      contractAddress:
        type: string
      cumulativeGasUsed:
        type: integer
      gas:
        type: integer
      gasPrice:
        type: string
      gasUsed:
        type: integer
      input:
        type: string
      nonce:
        type: integer
      root:
        items:
          type: integer
        type: array
      status:
        type: string
      to:
        type: string
      transactionHash:
        type: string
      transactionIndex:
        type: integer
      value:
        type: string
    type: object
  dao.TxAnchorsNode:
    properties:
      anchor_id:
        type: integer
      anchorAddress:
        description: 锚定节点地址
        type: string
      chain_id:
        type: integer
      contractAddress:
        description: 跨链合约地址
        type: string
      count:
        type: string
      date:
        type: string
      fee:
        type: integer
      name:
        type: string
      source_chain_id:
        type: integer
      source_network_id:
        type: integer
      target_chain_id:
        type: integer
      target_network_id:
        type: integer
      timeType:
        type: string
    type: object
  dao.Wallet:
    properties:
      address:
        type: string
      content:
        items:
          type: integer
        type: array
      name:
        type: string
      userId:
        type: integer
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/contract/instance/import:
    post:
      consumes:
      - application/x-www-form-urlencoded
      - application/json
      description: 引用链上合约
      parameters:
      - description: 请求体
        in: body
        name: '""'
        required: true
        schema:
          $ref: '#/definitions/controllers.ExistsContractParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.JsonResult'
      summary: 引用链上合约
  /api/v1/contract/register/once:
    post:
      consumes:
      - application/x-www-form-urlencoded
      - application/json
      description: 引用链上合约
      parameters:
      - description: 请求体
        in: body
        name: '""'
        required: true
        schema:
          $ref: '#/definitions/controllers.ExistsContractParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.JsonResult'
      summary: 引用链上合约
  /block/list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.JsonResult'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/controllers.Block'
                  type: array
              type: object
      security:
      - ApiKeyAuth: []
      summary: 分页获取区块列表
      tags:
      - block
  /block/transaction/{hash}:
    get:
      consumes:
      - application/json
      parameters:
      - description: tx hash
        in: query
        name: hash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.JsonResult'
            - properties:
                data:
                  $ref: '#/definitions/controllers.TransactionReceipt'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 交易详情
      tags:
      - block
  /block/transaction/{number}:
    get:
      consumes:
      - application/json
      parameters:
      - description: blockNumber
        in: query
        name: number
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.JsonResult'
            - properties:
                data:
                  $ref: '#/definitions/controllers.Transaction'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 分页列表
      tags:
      - block
  /chain/{chain_id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: chainId
        in: path
        name: chain_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功删除链信息
          schema:
            allOf:
            - $ref: '#/definitions/controllers.JsonResult'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 删除链信息
      tags:
      - chain
  /chart/feeAndCount/list:
    get:
      consumes:
      - application/json
      parameters:
      - description: hour:2020-07-10 12:00:00 day:2020-07-10 week:202025
        in: query
        name: startTime
        required: true
        type: string
      - description: hour:2020-07-12 12:00:00 day:2020-07-12 week:202027
        in: query
        name: endTime
        required: true
        type: string
      - description: chainId
        in: query
        name: chainId
        required: true
        type: integer
      - description: hour,day,week
        in: query
        name: timeType
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.JsonResult'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dao.TxAnchorsNode'
                  type: array
              type: object
      summary: 统计锚定节点验证数和手续费
      tags:
      - Chart
  /node:
    post:
      consumes:
      - application/json
      parameters:
      - description: 关联链Id
        in: formData
        name: chain_id
        required: true
        type: integer
      - description: 节点地址
        in: formData
        name: address
        required: true
        type: string
      - description: 端口
        in: formData
        name: port
        required: true
        type: integer
      - description: 名称
        in: formData
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: NodeId
          schema:
            allOf:
            - $ref: '#/definitions/controllers.JsonResult'
            - properties:
                data:
                  type: integer
              type: object
      security:
      - ApiKeyAuth: []
      summary: 添加node
      tags:
      - node
  /node/change:
    post:
      consumes:
      - application/json
      parameters:
      - description: useId
        in: formData
        name: user_id
        required: true
        type: integer
      - description: nodeId
        in: formData
        name: node_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 切换node
      tags:
      - node
  /node/current:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.JsonResult'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/controllers.Node'
                  type: array
              type: object
      security:
      - ApiKeyAuth: []
      summary: 获取当前登录账户的节点
      tags:
      - node
  /node/list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.JsonResult'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/controllers.Node'
                  type: array
              type: object
      security:
      - ApiKeyAuth: []
      summary: 节点列表
      tags:
      - node
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"token": token, "user_id": loadUser.ID}'
          schema:
            allOf:
            - $ref: '#/definitions/controllers.JsonResult'
            - properties:
                data:
                  type: object
              type: object
      summary: 用户登录
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":"用户Id"}'
          schema:
            allOf:
            - $ref: '#/definitions/controllers.JsonResult'
            - properties:
                data:
                  type: integer
              type: object
      summary: 用户注册
      tags:
      - user
  /wallet:
    post:
      consumes:
      - application/json
      parameters:
      - description: 钱包昵称
        in: formData
        name: name
        required: true
        type: string
      - description: keystore string
        in: formData
        name: content
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: walletId
          schema:
            allOf:
            - $ref: '#/definitions/controllers.JsonResult'
            - properties:
                data:
                  type: integer
              type: object
      security:
      - ApiKeyAuth: []
      summary: 添加钱包
      tags:
      - wallet
  /wallet/list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.JsonResult'
            - properties:
                data:
                  $ref: '#/definitions/dao.Wallet'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 钱包列表
      tags:
      - wallet
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
